version: '2'

services:
    db:
        image: postgres
        ports:
        - "5432:5432"
        environment:
        - POSTGRES_PASSWORD=${pg_pass}
        - POSTGRES_USER=${pg_user}
        - POSTGRES_DB=${pg_db}
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    composer:
        image: "composer"
        working_dir: /var/www/symfony
        command: install
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony"
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
